/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConduitRouteImport } from './routes/conduit'
import { Route as HuggingfaceRouteImport } from './routes/huggingface'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConduitRoute = ConduitRouteImport.update({
  id: '/conduit',
  path: '/conduit',
  getParentRoute: () => rootRouteImport,
} as any)
const HuggingfaceRoute = HuggingfaceRouteImport.update({
  id: '/huggingface',
  path: '/huggingface',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conduit': typeof ConduitRoute
  '/huggingface': typeof HuggingfaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conduit': typeof ConduitRoute
  '/huggingface': typeof HuggingfaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conduit': typeof ConduitRoute
  '/huggingface': typeof HuggingfaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/conduit' | '/huggingface'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/conduit' | '/huggingface'
  id: '__root__' | '/' | '/conduit' | '/huggingface'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConduitRoute: typeof ConduitRoute
  HuggingfaceRoute: typeof HuggingfaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conduit': {
      id: '/conduit'
      path: '/conduit'
      fullPath: '/conduit'
      preLoaderRoute: typeof ConduitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huggingface': {
      id: '/huggingface'
      path: '/huggingface'
      fullPath: '/huggingface'
      preLoaderRoute: typeof HuggingfaceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConduitRoute: ConduitRoute,
  HuggingfaceRoute: HuggingfaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
